/*
 * ExportDialog.java
 *
 * Created on June 19, 2007, 1:00 PM
 */

package com.datavirtue.nevitium.ui;
import com.datavirtue.nevitium.services.util.DV;
import com.datavirtue.nevitium.ui.util.ProgressDialogInterface;
import javax.swing.JFileChooser;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author  Data Virtue
 */
public class ExportDialog extends javax.swing.JDialog implements Runnable,  ProgressDialogInterface {
    
    /** Creates new form ExportDialog */
    public ExportDialog(java.awt.Frame parent, boolean modal) {
        super(parent, false);
        initComponents();
        Toolkit tools = Toolkit.getDefaultToolkit();
        Image winIcon = tools.getImage(getClass().getResource("/businessmanager/res/Orange.png"));
        this.setIconImage(winIcon);
                
        String path = System.getProperty("user.home");
        if (System.getProperty("os.name").contains("Windows")) path = path + "\\My Documents\\";
        
        dirField.setText(path);
        
        jProgressBar1.setMinimum(0);
        
        java.awt.Dimension dim = DV.computeCenter((java.awt.Window) this);
        
        this.setLocation(dim.width, dim.height);
        
        this.setVisible(true);
        
        new Thread(this).start();
        
        
        
    }
   
        
    private String n = System.getProperty ("line.separator");
    
        public void run () {
        
        
        try{synchronized(this){wait();}}
            catch (InterruptedException e){}
        
                
        String dir = dirField.getText().trim();
        
        dir = DV.verifyPath(dir);
        
        if (connBox.isSelected()){
                  
            int [] connFields = {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16};
            
               //db.csvExport("conn", new java.io.File(dir + "Connections.csv"), connFields, this);
               connBox.setSelected(false);
               
        }
        
        
        if (inventoryBox.isSelected()){
        
            int [] inventoryFields = {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18};
            jProgressBar1.setValue(0);
            //db.csvExport("inventory", new java.io.File(dir + "Inventory.csv"), inventoryFields, this);
             inventoryBox.setSelected(false);
             
        }
        
        if (invBox.isSelected()){
        
            int [] invFields = {0,1,2,3,4,5,6,7,8,9,10,11};
            int [] itemFields = {0,1,2,3,4,5,6,7,8,9};
            
            //new ExportProgressDialog(null, true, db, "invoice", invFields, new java.io.File(dir + "Invoices.csv"), "Exporting Invoices", false );
            //jProgressBar1.setValue(0);
            //db.csvExport("invoice", new java.io.File(dir + "Invoices.csv"), invFields, this);
            
                        
            //new ExportProgressDialog(null, true, db, "invitems", itemFields, new java.io.File(dir + "Invoice_Items.csv"), "Exporting Invoice Items", false );
           //jProgressBar1.setValue(0);
            //db.csvExport("invitems", new java.io.File(dir + "Invoice_Items.csv"), itemFields, this);
            invBox.setSelected(false);                        
        }
        
        if (payBox.isSelected()){
        
            int [] payFields = {0,1,2,3,4,5,6};
                      
            //new ExportProgressDialog(null, true, db, "payments", payFields, new java.io.File(dir + "Invoice_Payments.csv"), "Exporting Invoice Payments", false );
            //jProgressBar1.setValue(0);
            //db.csvExport("payments", new java.io.File(dir + "Invoice_Payments.csv"), payFields, this);
             payBox.setSelected(false);           
        }
        
        this.dispose();        
    }
    
     /* Reach in methods to update the JProgressBar  */
    public void setBarMax(int value){
        
        jProgressBar1.setMaximum(value);
        
    }
    
    public void updateBar (int value){
        
        jProgressBar1.setValue(value);
        
    }
    
    public void close() {
        
        
        //this.dispose();
        
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        connBox = new javax.swing.JCheckBox();
        inventoryBox = new javax.swing.JCheckBox();
        invBox = new javax.swing.JCheckBox();
        payBox = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        dirField = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        defaultPathbutton = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nevitium Basic Export");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        connBox.setSelected(true);
        connBox.setText("Connections");
        connBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        connBox.setMargin(new java.awt.Insets(0, 0, 0, 0));

        inventoryBox.setSelected(true);
        inventoryBox.setText("Inventory");
        inventoryBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        inventoryBox.setMargin(new java.awt.Insets(0, 0, 0, 0));

        invBox.setSelected(true);
        invBox.setText("Invoices & Invoice Items");
        invBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        invBox.setMargin(new java.awt.Insets(0, 0, 0, 0));

        payBox.setSelected(true);
        payBox.setText("Invoice Payments");
        payBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        payBox.setMargin(new java.awt.Insets(0, 0, 0, 0));

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .add(connBox)
                    .add(inventoryBox)
                    .add(invBox)
                    .add(payBox))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(connBox)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(inventoryBox)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(invBox)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(payBox)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("Destination Directory / Folder");

        browseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/businessmanager/res/Aha-24/enabled/Find in folder.png"))); // NOI18N
        browseButton.setText("Browse");
        browseButton.setToolTipText("Select the folder you want the exports to end up at");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/businessmanager/res/Aha-24/enabled/Play.png"))); // NOI18N
        jButton2.setToolTipText("Select the destination and click GO to export");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        defaultPathbutton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        defaultPathbutton.setText("Default");
        defaultPathbutton.setToolTipText("restore default destination");
        defaultPathbutton.setMargin(new java.awt.Insets(2, 10, 2, 10));
        defaultPathbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultPathbuttonActionPerformed(evt);
            }
        });

        jProgressBar1.setToolTipText("Export progress bar");

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(dirField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(jLabel3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 207, Short.MAX_VALUE)
                        .add(defaultPathbutton))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                        .add(jButton2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 225, Short.MAX_VALUE)
                        .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(browseButton))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jProgressBar1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(defaultPathbutton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dirField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(23, 23, 23)
                        .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jButton2)
                        .add(browseButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jProgressBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(32, 32, 32))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel3, 0, 132, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void defaultPathbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultPathbuttonActionPerformed
        
        String path = System.getProperty("user.home");
        if (System.getProperty("os.name").contains("Windows")) path = path + "\\My Documents\\";
        
        dirField.setText(path);
        
    }//GEN-LAST:event_defaultPathbuttonActionPerformed

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        
        JFileChooser fileChooser = DV.getDirChooser(dirField.getText(), null);
            
        java.io.File curFile = fileChooser.getSelectedFile();
        if (curFile != null ) dirField.setText( DV.verifyPath(curFile.toString()) );
        else dirField.setText("");
        
    }//GEN-LAST:event_browseButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

      
        defaultPathbutton.setEnabled(false);
        browseButton.setEnabled(false);
        jButton2.setEnabled(false);
        
         synchronized(this){notifyAll();}
        
        
    }//GEN-LAST:event_jButton2ActionPerformed
    
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseButton;
    private javax.swing.JCheckBox connBox;
    private javax.swing.JButton defaultPathbutton;
    private javax.swing.JTextField dirField;
    private javax.swing.JCheckBox invBox;
    private javax.swing.JCheckBox inventoryBox;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JCheckBox payBox;
    // End of variables declaration//GEN-END:variables
    
}
