package com.datavirtue.nevitium.ui;

import java.io.File;
import java.io.IOException;
import java.util.prefs.BackingStoreException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import com.datavirtue.nevitium.services.LocalSettingsService;
import com.datavirtue.nevitium.models.settings.LocalAppSettings;
import com.datavirtue.nevitium.services.ExceptionService;
import com.datavirtue.nevitium.services.util.DV;

/**
 *
 * @author SeanAnderson
 */
public class LocalSettingsDialog extends javax.swing.JDialog {

    /**
     * Creates new form FirstContactDialog
     */
    public LocalSettingsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();                
        
         java.awt.Dimension dim = DV.computeCenter((java.awt.Window) this);
        
        this.setLocation(dim.width, dim.height);
        
        this.themeComboBox.setModel(new DefaultComboBoxModel(LocalSettingsService.THEME_NAMES));
    }
    private boolean freshRun = false;
    
    
    public void display() throws BackingStoreException {

        var localSettings = LocalSettingsService.getLocalAppSettings();

        if (localSettings == null) { // new settings
            freshRun = true;
            localSettings = LocalSettingsService.createDefaultLocalAppSettings();
            populateForm(localSettings);
            this.setVisible(true);
        }

    }

    private String getPathFromUser() throws IOException {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int option = fileChooser.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            this.filenameTextField.setText(file.getCanonicalPath());            
        } 
        
        return "~/";        
    }

    private void populateForm(LocalAppSettings localSettings) {

        this.filenameTextField.setEditable(freshRun);
        this.connectionStringTemplateTextField.setEditable(freshRun);
        this.themeComboBox.setSelectedItem(LocalSettingsService.DEFAULT_THEME);
        if (this.freshRun) {
            this.filenameTextField.setText(LocalSettingsService.DEFAULT_DATA_PATH);
            this.connectionStringTemplateTextField.setText("jdbc:h2:%filename%;AUTO_SERVER=TRUE");
            this.effectiveConnectionStringTextField.setText(LocalSettingsService.DEFAULT_CONNECTION_STRING);
        } else {
            this.effectiveConnectionStringTextField.setText(localSettings.getConnectionString());
        }
    }

    private void saveLocalSettings() {

        var localSettings = new LocalAppSettings();

        localSettings.setConnectionString(this.effectiveConnectionStringTextField.getText());
        localSettings.setDataPath(this.filenameTextField.getText());
        localSettings.setTheme((String)this.themeComboBox.getSelectedItem());
        
        try {
            LocalSettingsService.saveLocalAppSettings(localSettings);
        } catch (BackingStoreException ex) {
            ExceptionService.showErrorDialog(this, ex, "Error saving local user settings");
        }
    }

    private void updateDerivedConnectionString() {
        var filepath = this.filenameTextField.getText();
        var connStringTemplate = this.connectionStringTemplateTextField.getText();
        var effective = connStringTemplate.replace("%filename%", filepath);
        this.effectiveConnectionStringTextField.setText(effective);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        handHoldingTextPane = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        filenameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        connectionStringTemplateTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        effectiveConnectionStringTextField = new javax.swing.JTextField();
        restoredDefaultsButton = new javax.swing.JButton();
        editSettingsCheckBox = new javax.swing.JCheckBox();
        importSettingsButton = new javax.swing.JButton();
        browseFilePathButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        themeComboBox = new javax.swing.JComboBox<>();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        helperPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        handHoldingTextPane.setText("We didn't find any local settings for you.. Some default settings were created for you and are shown below. It is often acceptable, especially when just started out, to accept the defaults.");
        jScrollPane1.setViewportView(handHoldingTextPane);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nevitium - Local User Settings");
        setAlwaysOnTop(true);

        filenameTextField.setEditable(false);
        filenameTextField.setToolTipText("");
        filenameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filenameTextFieldActionPerformed(evt);
            }
        });
        filenameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                filenameTextFieldKeyTyped(evt);
            }
        });

        jLabel2.setText("Database connection string helper template");

        connectionStringTemplateTextField.setEditable(false);
        connectionStringTemplateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectionStringTemplateTextFieldActionPerformed(evt);
            }
        });
        connectionStringTemplateTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                connectionStringTemplateTextFieldKeyTyped(evt);
            }
        });

        jLabel1.setText("Database path + filename  = %filename%");

        jLabel4.setText("Effective connection string");

        restoredDefaultsButton.setText("Use Default");
        restoredDefaultsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restoredDefaultsButtonActionPerformed(evt);
            }
        });

        editSettingsCheckBox.setText("Edit ");
        editSettingsCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSettingsCheckBoxActionPerformed(evt);
            }
        });

        importSettingsButton.setText("Import");

        browseFilePathButton.setText("Browse");
        browseFilePathButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseFilePathButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(connectionStringTemplateTextField)
                    .addComponent(filenameTextField)
                    .addComponent(effectiveConnectionStringTextField)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(editSettingsCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(importSettingsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(restoredDefaultsButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                        .addComponent(browseFilePathButton)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(browseFilePathButton)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filenameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(connectionStringTemplateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(effectiveConnectionStringTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(restoredDefaultsButton)
                    .addComponent(editSettingsCheckBox)
                    .addComponent(importSettingsButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("Theme");

        themeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(themeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(themeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        helperPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Help Text"));

        jScrollPane2.setViewportView(jTextPane1);

        javax.swing.GroupLayout helperPanelLayout = new javax.swing.GroupLayout(helperPanel);
        helperPanel.setLayout(helperPanelLayout);
        helperPanelLayout.setHorizontalGroup(
            helperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(helperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        helperPanelLayout.setVerticalGroup(
            helperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(helperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(helperPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(helperPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filenameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filenameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filenameTextFieldActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        this.saveLocalSettings();
        this.dispose();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void filenameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filenameTextFieldKeyTyped
        updateDerivedConnectionString();
    }//GEN-LAST:event_filenameTextFieldKeyTyped

    private void connectionStringTemplateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectionStringTemplateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_connectionStringTemplateTextFieldActionPerformed

    private void connectionStringTemplateTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_connectionStringTemplateTextFieldKeyTyped
        updateDerivedConnectionString();
    }//GEN-LAST:event_connectionStringTemplateTextFieldKeyTyped

    private void restoredDefaultsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restoredDefaultsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_restoredDefaultsButtonActionPerformed

    private void editSettingsCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSettingsCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editSettingsCheckBoxActionPerformed

    private void browseFilePathButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseFilePathButtonActionPerformed
        try {
            getPathFromUser();
        } catch (IOException ex) {
            ExceptionService.showErrorDialog(this, ex, "Error resolving the path");
        }
    }//GEN-LAST:event_browseFilePathButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        if (this.freshRun) {
            System.exit(1);
        } else {
          this.dispose();
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LocalSettingsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LocalSettingsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LocalSettingsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LocalSettingsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LocalSettingsDialog dialog = new LocalSettingsDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseFilePathButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField connectionStringTemplateTextField;
    private javax.swing.JCheckBox editSettingsCheckBox;
    private javax.swing.JTextField effectiveConnectionStringTextField;
    private javax.swing.JTextField filenameTextField;
    private javax.swing.JTextPane handHoldingTextPane;
    private javax.swing.JPanel helperPanel;
    private javax.swing.JButton importSettingsButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton restoredDefaultsButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox<String> themeComboBox;
    // End of variables declaration//GEN-END:variables
}
