/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StatusDialog.java
 *
 * Created on Aug 14, 2009, 12:59:47 AM
 */

package com.datavirtue.nevitium.ui;
import com.datavirtue.nevitium.services.util.DV;


/**
 *
 * @author Data Virtue
 */
public class StatusDialog extends javax.swing.JDialog {

    /** Creates new form StatusDialog */
    public StatusDialog(java.awt.Frame parent, boolean modal, String title, boolean decorated) {
        super(parent, modal);
        initComponents();
        this.setTitle(title);
        this.setDefaultLookAndFeelDecorated(decorated);
        java.awt.Dimension dim = DV.computeCenter((java.awt.Window) this);

        this.setLocation(dim.width, dim.height);

        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        statusPane = new javax.swing.JTextPane();
        staticMessageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Status");
        setAlwaysOnTop(true);
        setResizable(false);

        statusPane.setEditable(false);
        statusPane.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        statusPane.setForeground(new java.awt.Color(102, 102, 102));
        jScrollPane1.setViewportView(statusPane);

        staticMessageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        staticMessageLabel.setText("Status");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(12, 12, 12)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, staticMessageLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(staticMessageLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void changeMessage(String m){

        staticMessageLabel.setText(m);
        this.validate();
    }

    public void changeStatus(String m){
        statusPane.setText(m);
        this.validate();
    }
    private String nl = System.getProperty("line.separator");
    public void addStatus(String m){
        
        statusPane.setText(statusPane.getText() + nl + m);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel staticMessageLabel;
    private javax.swing.JTextPane statusPane;
    // End of variables declaration//GEN-END:variables

}
