/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PrintPreview.java
 *
 * Created on Apr 26, 2011, 11:27:13 PM
 */

package com.datavirtue.nevitium.ui.layoutdesigner;

import com.datavirtue.nevitium.services.util.DV;
import com.datavirtue.nevitium.ui.util.PrintPanel;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.print.Book;
import java.awt.print.PrinterJob;
import javax.swing.JPanel;

/**
 *
 * @author dataVirtue
 */
public class PrintPreview extends javax.swing.JDialog {
private Book theBook;
private PrintPanel thePanel;
private float[] pageSize;
private Image winIcon;
    /** Creates new form PrintPreview */
    public PrintPreview(Book b, float[] pageSize) {
        
        Toolkit tools = Toolkit.getDefaultToolkit();
        winIcon = tools.getImage(getClass().getResource("/businessmanager/res/Aha-16/enabled/Preview.png"));
        
        initComponents();
                               
        
        //this.setPreferredSize(new Dimension(800, 900));
        this.setVisible(true);
        this.pageSize = pageSize;
        theBook = b;
        
        thePanel = (PrintPanel)theBook.getPrintable(currentPage);
        thePanel.setPreferredSize(new Dimension((int)pageSize[0],(int)pageSize[1])); ///need to set dynamically
        pageLabel.setText((currentPage+1)+" of "+b.getNumberOfPages());
        this.add(thePanel);
        
        this.setResizable(true);
        this.pack();
        java.awt.Dimension dim = DV.computeCenter((java.awt.Window) this);
        this.setLocation(dim.width, dim.height);

    }

    private void reposition(){
        
        
        
        //this.repaint();
        this.pack();
        java.awt.Dimension dim = DV.computeCenter((java.awt.Window) this);
        this.setLocation(dim.width, dim.height);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        printButton = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        firstButton = new javax.swing.JButton();
        reverseButton = new javax.swing.JButton();
        zoomOutButton = new javax.swing.JButton();
        pageLabel = new javax.swing.JLabel();
        zoomInButton = new javax.swing.JButton();
        fwButton = new javax.swing.JButton();
        lastButton = new javax.swing.JButton();
        pdfButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Print Preview");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(winIcon);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        printButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/businessmanager/res/Aha-24/enabled/Print.png"))); // NOI18N
        printButton.setFocusable(false);
        printButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        printButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        firstButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/businessmanager/res/Aha-24/hot/First.png"))); // NOI18N
        firstButton.setFocusable(false);
        firstButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        firstButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        firstButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(firstButton);

        reverseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/businessmanager/res/Aha-24/hot/Back.png"))); // NOI18N
        reverseButton.setFocusable(false);
        reverseButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reverseButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        reverseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reverseButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(reverseButton);

        zoomOutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/businessmanager/res/Aha-24/enabled/Zoom out.png"))); // NOI18N
        zoomOutButton.setFocusable(false);
        zoomOutButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        zoomOutButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        zoomOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoomOutButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(zoomOutButton);

        pageLabel.setText("Pages");
        jToolBar1.add(pageLabel);

        zoomInButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/businessmanager/res/Aha-24/enabled/Zoom in.png"))); // NOI18N
        zoomInButton.setFocusable(false);
        zoomInButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        zoomInButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        zoomInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoomInButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(zoomInButton);

        fwButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/businessmanager/res/Aha-24/hot/Forward.png"))); // NOI18N
        fwButton.setFocusable(false);
        fwButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fwButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        fwButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fwButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(fwButton);

        lastButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/businessmanager/res/Aha-24/hot/Last.png"))); // NOI18N
        lastButton.setFocusable(false);
        lastButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lastButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lastButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(lastButton);

        pdfButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/businessmanager/res/Aha-24/enabled/Internet.png"))); // NOI18N
        pdfButton.setFocusable(false);
        pdfButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        pdfButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pdfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdfButtonActionPerformed(evt);
            }
        });

        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(printButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pdfButton)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pdfButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(printButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        PrinterJob printJob = PrinterJob.getPrinterJob();
        printJob.setPageable(theBook);
        if (printJob.printDialog()) {
        try {
            printJob.print();
        } catch (Exception prt) {
            System.err.println(prt.getMessage());
        }
        }
    }//GEN-LAST:event_printButtonActionPerformed

    private void fwButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fwButtonActionPerformed

        //if ((currentPage+1)==theBook.getNumberOfPages()) return;

        this.remove((PrintPanel)theBook.getPrintable(currentPage));
        
        currentPage++;
        if ((currentPage)==theBook.getNumberOfPages()) currentPage = 0;
        
        
        PrintPanel pp = (PrintPanel)theBook.getPrintable(currentPage);
        pp.setDocumentScale(currentScale);
        pp.setPreferredSize(new Dimension((int)(pageSize[0]*currentScale), (int)(pageSize[1]*currentScale)));
        this.add((JPanel)pp);
        
        /*this.add((JPanel)theBook.getPrintable(currentPage));*/
        pageLabel.setText((currentPage+1)+" of "+theBook.getNumberOfPages());
        //thePanel.getRootPane().revalidate();
        //this.repaint();
        this.reposition();
        
    }//GEN-LAST:event_fwButtonActionPerformed

    private void reverseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reverseButtonActionPerformed
        //if ((currentPage-1)<0) return;

        this.remove((PrintPanel)theBook.getPrintable(currentPage));
        currentPage--;
        if ((currentPage) < 0) currentPage = theBook.getNumberOfPages()-1;
        
         PrintPanel pp = (PrintPanel)theBook.getPrintable(currentPage);
        pp.setDocumentScale(currentScale);
        pp.setPreferredSize(new Dimension((int)(pageSize[0]*currentScale), (int)(pageSize[1]*currentScale)));
        this.add((JPanel)pp);
        
        
        /*this.add((JPanel)theBook.getPrintable(currentPage));*/
        pageLabel.setText((currentPage+1)+" of "+theBook.getNumberOfPages());
        //thePanel.getRootPane().revalidate();
        //this.repaint();
        this.reposition();
        
    }//GEN-LAST:event_reverseButtonActionPerformed

    private void firstButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstButtonActionPerformed
        this.remove((PrintPanel)theBook.getPrintable(currentPage));
        currentPage=0;
        
         PrintPanel pp = (PrintPanel)theBook.getPrintable(currentPage);
        pp.setDocumentScale(currentScale);
        pp.setPreferredSize(new Dimension((int)(pageSize[0]*currentScale), (int)(pageSize[1]*currentScale)));
        this.add((JPanel)pp);
        
        /*
        this.add((JPanel)theBook.getPrintable(currentPage));*/
        pageLabel.setText((currentPage+1)+" of "+theBook.getNumberOfPages());
        //thePanel.getRootPane().revalidate();
        //this.repaint();
        this.reposition();
    }//GEN-LAST:event_firstButtonActionPerformed

    private void lastButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastButtonActionPerformed
        this.remove((PrintPanel)theBook.getPrintable(currentPage));
        currentPage=theBook.getNumberOfPages()-1;
        
         PrintPanel pp = (PrintPanel)theBook.getPrintable(currentPage);
        pp.setDocumentScale(currentScale);
        pp.setPreferredSize(new Dimension((int)(pageSize[0]*currentScale), (int)(pageSize[1]*currentScale)));
        this.add((JPanel)pp);
        
        /*this.add((JPanel)theBook.getPrintable(currentPage));*/
        pageLabel.setText((currentPage+1)+" of "+theBook.getNumberOfPages());
                
        //this.repaint();
        this.reposition();
    }//GEN-LAST:event_lastButtonActionPerformed

private void pdfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdfButtonActionPerformed
        
}//GEN-LAST:event_pdfButtonActionPerformed

    private void zoomOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoomOutButtonActionPerformed
        currentScale = currentScale - .10;
        this.remove((PrintPanel)theBook.getPrintable(currentPage));
        PrintPanel pp = (PrintPanel)theBook.getPrintable(currentPage);
        pp.setDocumentScale(currentScale);
        pp.setPreferredSize(new Dimension((int)(pageSize[0]*currentScale), (int)(pageSize[1]*currentScale)));
        this.add((JPanel)pp);
        //this.repaint();
        this.reposition();
    }//GEN-LAST:event_zoomOutButtonActionPerformed

    private void zoomInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoomInButtonActionPerformed
        currentScale = currentScale + .10;
        this.remove((PrintPanel)theBook.getPrintable(currentPage));
        PrintPanel pp = (PrintPanel)theBook.getPrintable(currentPage);
        pp.setDocumentScale(currentScale);
        pp.setPreferredSize(new Dimension((int)(pageSize[0]*currentScale), (int)(pageSize[1]*currentScale)));
        this.add((JPanel)pp);
        //this.repaint();
        this.reposition();
    }//GEN-LAST:event_zoomInButtonActionPerformed

  private int currentPage = 0;
  private double currentScale=1.0;
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton firstButton;
    private javax.swing.JButton fwButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton lastButton;
    private javax.swing.JLabel pageLabel;
    private javax.swing.JButton pdfButton;
    private javax.swing.JButton printButton;
    private javax.swing.JButton reverseButton;
    private javax.swing.JButton zoomInButton;
    private javax.swing.JButton zoomOutButton;
    // End of variables declaration//GEN-END:variables

}
