/*
 * InventoryGroupDialog.java
 *
 * Created on April 28, 2007, 10:37 AM
 */

package com.datavirtue.nevitium.ui.inventory;
import com.datavirtue.nevitium.services.util.DV;
import java.io.*;
import javax.swing.DefaultListModel;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author  Data Virtue
 */
public class InventoryGroupDialog extends javax.swing.JDialog {
    
    /** Creates new form InventoryGroupDialog */
    public InventoryGroupDialog(java.awt.Frame parent, boolean modal, int [] keys, String path) {
        
        super(parent, modal);
        initComponents();
        Toolkit tools = Toolkit.getDefaultToolkit();
        Image winIcon = tools.getImage(getClass().getResource("/businessmanager/res/Orange.png"));
        this.setIconImage(winIcon);
        workingPath = path;
        java.awt.Dimension dim = DV.computeCenter((java.awt.Window) this);
        this.setLocation(dim.width, dim.height);
        
        this.keys = keys;
           
        populateGroups();    
        
    }

    private DefaultListModel lm;
    private int [] keys;
    private String workingPath = "";
    private void populateGroups () {
        
        lm = new javax.swing.DefaultListModel();
        
        
        String path = workingPath + "grps/";
        
        File dir = new File (path);
        if (!dir.exists()) dir.mkdirs();
        
        String [] files = dir.list();
        
        for (int i = files.length-1; i > -1; i--){
        
            lm.addElement(files[i]);
            
        }
        //if (files.length < 1) return;
        
        groupList.setModel(lm);
        
    }
    
    private void newGroup () {
        
        String iValue = javax.swing.JOptionPane.showInputDialog("Provide a unique group name:"); 

        if (iValue == null) return;
        if (iValue.equals("")) return;
        
          
        
        String tmp="";
        int elements = lm.getSize();
        
        boolean match=false;
        
        for (int e = 0; e < elements; e++){
            
            tmp = (String)lm.getElementAt(e);
            
            if (tmp.equals(iValue) ) match = true;
            
            
        }
        
        if (!match) 
        {
            
            File jFile = new File(workingPath + "grps/");
            
            if (!jFile.exists()) jFile.mkdirs();
            StringBuilder sb = new StringBuilder();
            
            for (int i = 0; i < keys.length; i++){
                
                if (i < keys.length-1) sb.append(Integer.toString(keys[i]) + System.getProperty("line.separator"));
                else sb.append(Integer.toString(keys[i]));
            }
            
            DV.writeFile(jFile.toString() + "/" + iValue, sb.toString(), false);
            lm.insertElementAt(iValue, 0);
            
           
        }else {
            
            javax.swing.JOptionPane.showMessageDialog(null, "You tried to create a group that already exists.");
            return;
        }
        
        
        
        
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        groupList = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inventory Groups");

        jScrollPane1.setViewportView(groupList);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/businessmanager/res/Aha-16/enabled/Create.png"))); // NOI18N
        jButton1.setText("Add");
        jButton1.setToolTipText("Adds from selected inventory items.");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/businessmanager/res/Aha-16/enabled/Delete.png"))); // NOI18N
        jButton2.setText("Remove");
        jButton2.setToolTipText("Instantly removes the selected group!");
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 127, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jButton3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jButton2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jButton1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(jButton1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jButton3)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        this.dispose();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        if (groupList.getSelectedIndex() < 0) return;
        
        String grp = (String)lm.getElementAt(groupList.getSelectedIndex());
        
        File f = new File (workingPath + "grps/"+grp);
        f.delete();
        populateGroups();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if (keys.length < 2) {
            
            javax.swing.JOptionPane.showMessageDialog(null, "You need to select more than one item from the inventory table.");
            return;
            
        }else newGroup();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList groupList;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
