/*
 * InventoryNoteDialog.java
 *
 * Created on December 7, 2008, 2:48 PM
 */

package com.datavirtue.nevitium.ui.inventory;
import com.datavirtue.nevitium.services.util.DV;
import com.datavirtue.nevitium.ui.util.LimitedDocument;
import javax.swing.*;
import java.awt.event.*;


/**
 *
 * @author  Data Virtue
 */
public class InventoryNoteDialog extends javax.swing.JDialog {
    
    /** Creates new form InventoryNoteDialog */
    public InventoryNoteDialog(java.awt.Frame parent, boolean modal, int key, String noteTitle) {
        super(parent, modal);
        initComponents();
        
        inventoryKey = key;
       
        noteTextArea.setDocument(new LimitedDocument(1024));
        
        
            /* Close dialog on escape */
        ActionMap am = getRootPane().getActionMap();
        InputMap im = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        Object windowCloseKey = new Object();
        KeyStroke windowCloseStroke = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0);
        Action windowCloseAction = new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                
                setVisible(false);
                dispose();
            }
        };
        
        java.awt.Dimension dim = DV.computeCenter((java.awt.Window) this);
        this.setLocation(dim.width, dim.height);
        
        noteTitleField.setText(noteTitle);
        getNote(inventoryKey);
        noteTextArea.requestFocus();
        
        this.setVisible(true);
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        noteTextArea = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        savebutton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        iconLabel = new javax.swing.JLabel();
        noteTitleField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inventory Notes");
        setAlwaysOnTop(true);
        setResizable(false);

        noteTextArea.setColumns(20);
        noteTextArea.setFont(new java.awt.Font("Courier", 0, 14)); // NOI18N
        noteTextArea.setLineWrap(true);
        noteTextArea.setRows(5);
        noteTextArea.setWrapStyleWord(true);
        noteTextArea.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        noteTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                noteTextAreaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(noteTextArea);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setToolTipText("Notes hava 512 character limit.");

        savebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/businessmanager/res/Aha-16/enabled/Floppy.png"))); // NOI18N
        savebutton.setText("Save");
        savebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebuttonActionPerformed(evt);
            }
        });

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/businessmanager/res/Aha-16/enabled/Close.png"))); // NOI18N
        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        iconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, iconLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, closeButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, savebutton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(iconLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(savebutton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(closeButton)
                .addContainerGap())
        );

        noteTitleField.setEditable(false);
        noteTitleField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        noteTitleField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(noteTitleField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 336, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(noteTitleField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void noteTextAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noteTextAreaKeyPressed
        
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ESCAPE) this.dispose();
        
        
    }//GEN-LAST:event_noteTextAreaKeyPressed

    private void savebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebuttonActionPerformed
        
        saveNote();        
        
    }//GEN-LAST:event_savebuttonActionPerformed

    private int noteKey = 0;

    private void getNote(int invKey) {
        
//        
//        Object [] note=null;
//        ArrayList al;
//        
//        al = db.search("invnotes", 1, Integer.toString(invKey), false);
//        
//        if (al != null){
//        
//            note = db.getRecord("invnotes", (Integer)al.get(0));
//            noteKey = (Integer) note[0];
//            noteTextArea.setText((String)note[2]);
//            noteTextArea.setCaretPosition(0);
//            
//        }else {
//            
//            noteKey = 0;
//            
//        }
//        
      
        
    }
    
    private void saveNote() {
        
        Object [] note = new Object [3];
        note[0] = new Integer(noteKey);
        note[1] = new Integer(inventoryKey);
        note[2] = new String (noteTextArea.getText());

        //noteKey = db.saveRecord("invnotes", note, false);
        
        this.dispose();
        
        
    }
    
    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        
        this.dispose();
        
    }//GEN-LAST:event_closeButtonActionPerformed
    
    
  private int inventoryKey;
  
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea noteTextArea;
    private javax.swing.JTextField noteTitleField;
    private javax.swing.JButton savebutton;
    // End of variables declaration//GEN-END:variables
    
}
