package com.datavirtue.axiom.ui.settings;

import java.io.File;
import java.io.IOException;
import java.util.prefs.BackingStoreException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import com.datavirtue.axiom.services.LocalSettingsService;
import com.datavirtue.axiom.models.settings.LocalAppSettings;
import com.datavirtue.axiom.services.ExceptionService;
import com.datavirtue.axiom.services.util.DV;
import org.apache.commons.lang3.StringUtils;

/**
 *
 * @author SeanAnderson
 */
public class LocalSettingsDialog extends javax.swing.JDialog {

    /**
     * @return the settingsSaved
     */
    private boolean settingsSaved = false;
    public boolean isSettingsSaved() {
        return settingsSaved;
    }

    /**
     * Creates new form FirstContactDialog
     */
    public LocalSettingsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        java.awt.Dimension dim = DV.computeCenter((java.awt.Window) this);

        this.setLocation(dim.width, dim.height);

        this.themeComboBox.setModel(new DefaultComboBoxModel(LocalSettingsService.THEME_NAMES));
    }

    
    public void displayApp() throws BackingStoreException {

        var localSettings = LocalSettingsService.getLocalAppSettings();

        if (localSettings == null) { // new settings
            localSettings = LocalSettingsService.createDefaultLocalAppSettings();
            populateForm(localSettings);
            this.setVisible(true);
        } else {
            populateForm(localSettings);
            this.setVisible(true);
        }

    }

    private String getPathFromUser() throws IOException {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int option = fileChooser.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            this.folderTextField.setText(file.getCanonicalPath());
        }

        return "~/";
    }

    private void populateForm(LocalAppSettings localSettings) {

        if (localSettings != null
                && (StringUtils.isBlank(localSettings.getDatabaseFolder())
                || StringUtils.isBlank(localSettings.getDatabaseFilename())
                || StringUtils.isBlank(localSettings.getDatabaseConnectionStringTemplate()))) {
            localSettings = LocalSettingsService.createDefaultLocalAppSettings();
        }

        if (StringUtils.isBlank(localSettings.getTheme())) {
            localSettings.setTheme(LocalSettingsService.DEFAULT_THEME);
        }
        
        this.folderTextField.setText(localSettings.getDatabaseFolder());
        this.filenameTextField.setText(localSettings.getDatabaseFilename());
        this.connectionStringTemplateTextField.setText(localSettings.getDatabaseConnectionStringTemplate());
        this.effectiveConnectionStringTextField.setText(localSettings.getConnectionString());
        this.themeComboBox.setSelectedItem(localSettings.getTheme());

    }

    private void saveLocalSettings() {

        var localSettings = new LocalAppSettings();

        localSettings.setDatabaseFolder(this.folderTextField.getText());
        localSettings.setDatabaseFilename(this.filenameTextField.getText());
        localSettings.setDatabaseConnectionStringTemplate(this.connectionStringTemplateTextField.getText());
        localSettings.setConnectionString(this.effectiveConnectionStringTextField.getText());
        localSettings.setTheme((String) this.themeComboBox.getSelectedItem());

        try {
            LocalSettingsService.saveLocalAppSettings(localSettings);
            this.settingsSaved = true;
        } catch (BackingStoreException ex) {
            ExceptionService.showErrorDialog(this, ex, "Error saving local user settings");
        }
    }

    private void updateDerivedConnectionString() {
        var folder = this.folderTextField.getText();
        var filename = this.filenameTextField.getText();
        var template = this.connectionStringTemplateTextField.getText();
        var connectionString = LocalSettingsService.buildConnectionString(folder, filename, template);
        this.effectiveConnectionStringTextField.setText(connectionString);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        handHoldingTextPane = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        folderTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        connectionStringTemplateTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        effectiveConnectionStringTextField = new javax.swing.JTextField();
        browseFilePathButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        filenameTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        themeComboBox = new javax.swing.JComboBox<>();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        importSettingsButton = new javax.swing.JButton();
        restoredDefaultsButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        handHoldingTextPane.setText("We didn't find any local settings for you.. Some default settings were created for you and are shown below. It is often acceptable, especially when just started out, to accept the defaults.");
        jScrollPane1.setViewportView(handHoldingTextPane);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Axiom - Local User Settings");
        setAlwaysOnTop(true);

        folderTextField.setToolTipText("The location of the database files. This should be a folder or directory specifically for the data files. The files can live alongside other files without issue though.");
        folderTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                folderTextFieldActionPerformed(evt);
            }
        });
        folderTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                folderTextFieldKeyReleased(evt);
            }
        });

        jLabel2.setText("Database connection string template");

        connectionStringTemplateTextField.setToolTipText("Databse connection string template where folder and filename are inserted automatically in place of %filename%");
        connectionStringTemplateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectionStringTemplateTextFieldActionPerformed(evt);
            }
        });
        connectionStringTemplateTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                connectionStringTemplateTextFieldKeyReleased(evt);
            }
        });

        jLabel1.setText("Database folder");

        jLabel4.setText("Effective connection string");

        effectiveConnectionStringTextField.setEditable(false);
        effectiveConnectionStringTextField.setToolTipText("This is built from the connection string folder, filename, and template from above. You can manually edit this string and save it.");

        browseFilePathButton.setText("Browse");
        browseFilePathButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseFilePathButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Database file name");

        filenameTextField.setToolTipText("Descriptive database name, normally named after the company. Try to avoid spaces, and instead use dashes.");
        filenameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filenameTextFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(folderTextField)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                        .addComponent(browseFilePathButton))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(connectionStringTemplateTextField)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(effectiveConnectionStringTextField)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filenameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(browseFilePathButton)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(folderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filenameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(connectionStringTemplateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(effectiveConnectionStringTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("Theme");

        themeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(themeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(themeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        importSettingsButton.setText("Import");
        importSettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importSettingsButtonActionPerformed(evt);
            }
        });

        restoredDefaultsButton.setText("Use Default");
        restoredDefaultsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restoredDefaultsButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Export");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(importSettingsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(restoredDefaultsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelButton)
                        .addGap(18, 18, 18)
                        .addComponent(saveButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(saveButton)
                        .addComponent(cancelButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(importSettingsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addComponent(restoredDefaultsButton)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void folderTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_folderTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_folderTextFieldActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        this.saveLocalSettings();
        this.dispose();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void connectionStringTemplateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectionStringTemplateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_connectionStringTemplateTextFieldActionPerformed

    private void restoredDefaultsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restoredDefaultsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_restoredDefaultsButtonActionPerformed

    private void browseFilePathButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseFilePathButtonActionPerformed
        try {
            getPathFromUser();
        } catch (IOException ex) {
            ExceptionService.showErrorDialog(this, ex, "Error resolving the path");
        }
    }//GEN-LAST:event_browseFilePathButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void folderTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_folderTextFieldKeyReleased
        updateDerivedConnectionString();
    }//GEN-LAST:event_folderTextFieldKeyReleased

    private void connectionStringTemplateTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_connectionStringTemplateTextFieldKeyReleased
        updateDerivedConnectionString();
    }//GEN-LAST:event_connectionStringTemplateTextFieldKeyReleased

    private void importSettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importSettingsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_importSettingsButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void filenameTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filenameTextFieldKeyReleased
        updateDerivedConnectionString();
    }//GEN-LAST:event_filenameTextFieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LocalSettingsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LocalSettingsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LocalSettingsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LocalSettingsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LocalSettingsDialog dialog = new LocalSettingsDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseFilePathButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField connectionStringTemplateTextField;
    private javax.swing.JTextField effectiveConnectionStringTextField;
    private javax.swing.JTextField filenameTextField;
    private javax.swing.JTextField folderTextField;
    private javax.swing.JTextPane handHoldingTextPane;
    private javax.swing.JButton importSettingsButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton restoredDefaultsButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox<String> themeComboBox;
    // End of variables declaration//GEN-END:variables
}
